//! A hardcoded list of expected 1.8.9 block/item texture names, used to
//! estimate a resource pack's coverage. 1.8.x resource packs use
//! `assets/minecraft/textures/blocks/` and `.../items/` (plural — this
//! changed to singular `block`/`item` in later versions), one 16x16 PNG
//! per name, no file extension listed here.
//!
//! This is NOT the complete vanilla 1.8.9 texture set (that runs to a
//! few hundred names once every wood/wool/dye/ore variant is counted) —
//! it's a representative sample covering the commonly-used blocks and
//! items, enough to give a meaningful coverage percentage without
//! shipping Mojang's own texture list verbatim.

pub const BLOCK_TEXTURES: &[&str] = &[
    "stone",
    "dirt",
    "grass_top",
    "grass_side",
    "grass_side_overlay",
    "cobblestone",
    "bedrock",
    "sand",
    "gravel",
    "gold_ore",
    "iron_ore",
    "coal_ore",
    "diamond_ore",
    "redstone_ore",
    "lapis_ore",
    "lapis_block",
    "gold_block",
    "iron_block",
    "diamond_block",
    "emerald_block",
    "emerald_ore",
    "planks_oak",
    "planks_spruce",
    "planks_birch",
    "planks_jungle",
    "planks_acacia",
    "planks_big_oak",
    "log_oak",
    "log_oak_top",
    "log_spruce",
    "log_spruce_top",
    "log_birch",
    "log_birch_top",
    "log_jungle",
    "log_jungle_top",
    "leaves_oak",
    "leaves_spruce",
    "leaves_birch",
    "leaves_jungle",
    "sapling_oak",
    "sapling_spruce",
    "sapling_birch",
    "sapling_jungle",
    "sponge",
    "glass",
    "sandstone_top",
    "sandstone_normal",
    "sandstone_bottom",
    "sandstone_carved",
    "noteblock",
    "bed_head_top",
    "bed_feet_top",
    "wool_colored_white",
    "wool_colored_orange",
    "wool_colored_magenta",
    "wool_colored_light_blue",
    "wool_colored_yellow",
    "wool_colored_lime",
    "wool_colored_pink",
    "wool_colored_gray",
    "wool_colored_silver",
    "wool_colored_cyan",
    "wool_colored_purple",
    "wool_colored_blue",
    "wool_colored_brown",
    "wool_colored_green",
    "wool_colored_red",
    "wool_colored_black",
    "flower_dandelion",
    "flower_rose",
    "mushroom_brown",
    "mushroom_red",
    "tnt_side",
    "tnt_top",
    "tnt_bottom",
    "stonebrick",
    "stonebrick_mossy",
    "stonebrick_cracked",
    "stonebrick_carved",
    "mob_spawner",
    "obsidian",
    "torch_on",
    "fire_layer_0",
    "fire_layer_1",
    "furnace_front_off",
    "furnace_side",
    "furnace_top",
    "furnace_front_on",
    "ladder",
    "rail_normal",
    "rail_golden",
    "rail_detector",
    "rail_activator",
    "clay",
    "reeds",
    "wheat_stage_7",
    "farmland_dry",
    "farmland_wet",
    "lever",
    "door_wood_upper",
    "door_wood_lower",
    "door_iron_upper",
    "door_iron_lower",
    "redstone_dust_line",
    "ice",
    "snow",
    "cactus_top",
    "cactus_side",
    "cactus_bottom",
    "pumpkin_top",
    "pumpkin_side",
    "pumpkin_face_off",
    "pumpkin_face_on",
    "netherrack",
    "soul_sand",
    "glowstone",
    "portal",
    "melon_side",
    "melon_top",
    "mycelium_top",
    "mycelium_side",
    "stone_slab_top",
    "stone_slab_side",
    "brick",
    "bookshelf",
    "cobblestone_mossy",
    "quartz_block_top",
    "quartz_block_side",
    "quartz_block_bottom",
    "quartz_block_chiseled",
    "water_still",
    "lava_still",
    "hardened_clay",
    "coal_block",
    "packed_ice",
    "red_sand",
    "dirt_podzol_top",
    "dirt_podzol_side",
];

pub const ITEM_TEXTURES: &[&str] = &[
    "apple",
    "arrow",
    "bow_standby",
    "coal",
    "diamond",
    "iron_ingot",
    "gold_ingot",
    "stick",
    "wood_sword",
    "stone_sword",
    "iron_sword",
    "diamond_sword",
    "golden_sword",
    "wood_pickaxe",
    "stone_pickaxe",
    "iron_pickaxe",
    "diamond_pickaxe",
    "golden_pickaxe",
    "wood_axe",
    "stone_axe",
    "iron_axe",
    "diamond_axe",
    "golden_axe",
    "wood_shovel",
    "stone_shovel",
    "iron_shovel",
    "diamond_shovel",
    "golden_shovel",
    "bucket_empty",
    "bucket_water",
    "bucket_lava",
    "bucket_milk",
    "bread",
    "egg",
    "feather",
    "flint",
    "gunpowder",
    "leather",
    "painting",
    "sign",
    "door_wood",
    "door_iron",
    "redstone_dust",
    "diamond_helmet",
    "diamond_chestplate",
    "diamond_leggings",
    "diamond_boots",
    "iron_helmet",
    "iron_chestplate",
    "iron_leggings",
    "iron_boots",
    "leather_helmet",
    "leather_chestplate",
    "leather_leggings",
    "leather_boots",
    "fishing_rod_uncast",
    "clock",
    "compass",
    "map_empty",
    "book_normal",
    "potion_bottle_drinkable",
    "glass_bottle",
    "spawn_egg",
    "gold_nugget",
    "emerald",
    "quartz",
    "nether_star",
    "record_13",
    "cookie",
    "melon",
    "pumpkin_pie",
    "carrot",
    "potato",
    "baked_potato",
    "poisonous_potato",
    "wheat",
    "seeds_wheat",
    "sugar",
    "string",
    "spider_eye",
    "fermented_spider_eye",
    "blaze_rod",
    "blaze_powder",
    "ghast_tear",
    "magma_cream",
    "ender_pearl",
    "ender_eye",
    "bone",
    "shears",
    "flint_and_steel",
];

/// Total number of textures this list expects a "complete" pack to
/// have, used as the denominator for coverage percentages.
pub fn total_known_textures() -> usize {
    BLOCK_TEXTURES.len() + ITEM_TEXTURES.len()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// A duplicate entry would silently deflate the coverage
    /// percentage (the denominator counts it twice, a real pack's
    /// texture only satisfies it once) — this test is here because
    /// exactly that bug slipped into an earlier draft of these lists.
    #[test]
    fn no_duplicate_names_within_each_list() {
        for (name, list) in [("BLOCK_TEXTURES", BLOCK_TEXTURES), ("ITEM_TEXTURES", ITEM_TEXTURES)] {
            let unique: HashSet<&str> = list.iter().copied().collect();
            assert_eq!(unique.len(), list.len(), "{name} contains a duplicate entry");
        }
    }
}
