[package]
name = "renderer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wgpu.workspace = true
winit.workspace = true
bytemuck.workspace = true
glam.workspace = true
client-core.workspace = true
texturepacks.workspace = true
ui.workspace = true
image.workspace = true
log.workspace = true
